import type { TemplateManifest } from '../../types';
import { createTheme, THEME_COLOR_FIELDS } from './shared';

export const newsletterDigestManifest = {
  id: 'newsletter-digest',
  name: 'Weekly digest',
  category: 'newsletter',
  description: 'A compact newsletter with three editorial highlights.',
  thumbnailPath: 'template-thumbnails/newsletter-digest.png',
  defaults: {
    templateId: 'newsletter-digest',
    schemaVersion: 1,
    theme: createTheme({ accentColor: '#0F766E' }),
    fields: {
      preheader: 'This week: product thinking, design systems, and growth.',
      logo: { remoteUrl: '', alt: 'Company logo' },
      heading: 'The Weekly Brief',
      intro: 'A focused selection of ideas worth your time this week.',
      article1Title: 'Build products people return to',
      article1Text: 'A practical framework for finding durable product value.',
      article1Image: { remoteUrl: '', alt: 'Product planning workspace' },
      article1Link: { label: 'Read article', url: 'https://example.com/article-1' },
      article2Title: 'Design systems that stay useful',
      article2Text: 'How to keep shared components aligned with real product work.',
      article2Image: { remoteUrl: '', alt: 'Interface component library' },
      article2Link: { label: 'Read article', url: 'https://example.com/article-2' },
      article3Title: 'A calmer approach to growth',
      article3Text: 'Measure the behaviors that create long-term customer value.',
      article3Image: { remoteUrl: '', alt: 'Growth report' },
      article3Link: { label: 'Read article', url: 'https://example.com/article-3' },
      primaryCta: { label: 'View all stories', url: 'https://example.com/stories' },
      showArticleImages: true,
      companyUrl: 'https://example.com',
      footerText: 'You are receiving this newsletter because you subscribed.',
    },
  },
  fields: [
    { key: 'preheader', type: 'text', label: 'Preheader', group: 'content', maxLength: 140 },
    { key: 'logo', type: 'image', label: 'Logo', group: 'brand', recommendedSize: '240 x 80 px' },
    { key: 'heading', type: 'text', label: 'Heading', group: 'content', maxLength: 80 },
    { key: 'intro', type: 'textarea', label: 'Introduction', group: 'content', maxLength: 320, rows: 4 },
    { key: 'article1Title', type: 'text', label: 'Article 1 title', group: 'content', maxLength: 100 },
    { key: 'article1Text', type: 'textarea', label: 'Article 1 summary', group: 'content', maxLength: 280, rows: 3 },
    { key: 'article1Image', type: 'image', label: 'Article 1 image', group: 'images', recommendedSize: '1120 x 560 px' },
    { key: 'article1Link', type: 'link', label: 'Article 1 link', group: 'content' },
    { key: 'article2Title', type: 'text', label: 'Article 2 title', group: 'content', maxLength: 100 },
    { key: 'article2Text', type: 'textarea', label: 'Article 2 summary', group: 'content', maxLength: 280, rows: 3 },
    { key: 'article2Image', type: 'image', label: 'Article 2 image', group: 'images', recommendedSize: '1120 x 560 px' },
    { key: 'article2Link', type: 'link', label: 'Article 2 link', group: 'content' },
    { key: 'article3Title', type: 'text', label: 'Article 3 title', group: 'content', maxLength: 100 },
    { key: 'article3Text', type: 'textarea', label: 'Article 3 summary', group: 'content', maxLength: 280, rows: 3 },
    { key: 'article3Image', type: 'image', label: 'Article 3 image', group: 'images', recommendedSize: '1120 x 560 px' },
    { key: 'article3Link', type: 'link', label: 'Article 3 link', group: 'content' },
    { key: 'primaryCta', type: 'link', label: 'Primary button', group: 'buttons' },
    { key: 'showArticleImages', type: 'toggle', label: 'Show article images', group: 'images' },
    { key: 'companyUrl', type: 'url', label: 'Company URL', group: 'footer' },
    { key: 'footerText', type: 'textarea', label: 'Footer text', group: 'footer', maxLength: 300, rows: 3 },
    ...THEME_COLOR_FIELDS,
  ],
} as const satisfies TemplateManifest;
