import type { TemplateManifest } from '../../types';
import { createTheme, THEME_COLOR_FIELD_KEYS, THEME_COLOR_FIELDS } from './shared';

const asset = (name: string, alt: string) => ({
  remoteUrl: `https://raw.githubusercontent.com/AlinaZolotavina/email-template-studio/main/public/template-assets/${name}`,
  localPreviewUrl: `${import.meta.env.BASE_URL}template-assets/${name}`,
  alt,
});

export const newsletterDigestManifest = {
  id: 'newsletter-digest',
  name: 'Weekly digest',
  category: 'newsletter',
  description: 'A compact newsletter with three editorial highlights.',
  thumbnailPath: 'template-thumbnails/newsletter-digest.png',
  defaults: {
    templateId: 'newsletter-digest',
    schemaVersion: 1,
    theme: createTheme({ accentColor: '#0F766E' }),
    fields: {
      showPreheader: true,
      showHeader: true,
      showArticles: true,
      showFooter: true,
      preheader: 'This week: product thinking, design systems, and growth.',
      logo: { remoteUrl: '', alt: 'Weekly Digest logo' },
      heading: 'Weekly digest',
      intro: 'Your weekly dose of insights, ideas, and inspiration.',
      articles: [
        { category: 'STRATEGY', title: 'Five ways to build better habits', text: 'Small changes, when done consistently, can lead to big results.', image: asset('digest-strategy.png', 'Abstract mountains and sun'), link: { label: 'Read more ->', url: 'https://example.com/article-1' } },
        { category: 'DATA', title: 'What the numbers are telling us', text: 'Key takeaways from the latest industry trends.', image: asset('digest-data.png', 'Ascending data chart'), link: { label: 'Read more ->', url: 'https://example.com/article-2' } },
        { category: 'CULTURE', title: 'Creating a culture of feedback', text: 'Why feedback matters - and how to make it part of your everyday.', image: asset('digest-culture.png', 'Conversation and feedback'), link: { label: 'Read more ->', url: 'https://example.com/article-3' } },
      ],
      primaryCta: { label: "Read this week's top stories", url: 'https://example.com/stories', backgroundColor: '#0F766E', textColor: '#FFFFFF' },
      showArticleImages: true,
      shareText: 'Enjoying the digest?',
      shareLink: { label: 'Share it with a friend.', url: 'https://example.com/share' },
      showSocialLinks: true,
      showFooterText: true,
      showLegalLinks: true,
      footerText: "You're receiving this email because you signed up for our updates.",
      socialLinks: [
        { label: 'X', url: 'https://example.com/x' },
        { label: 'in', url: 'https://example.com/linkedin' },
        { label: 'Email', url: 'mailto:hello@example.com' },
      ],
      legalLinks: [
        { label: 'Update preferences', url: 'https://example.com/preferences' },
        { label: 'Unsubscribe', url: 'https://example.com/unsubscribe' },
      ],
    },
  },
  fields: [
    { key: 'showPreheader', type: 'toggle', label: 'Show preheader', group: 'content' },
    { key: 'showHeader', type: 'toggle', label: 'Show header', group: 'content' },
    { key: 'showArticles', type: 'toggle', label: 'Show articles', group: 'content' },
    { key: 'showFooter', type: 'toggle', label: 'Show footer', group: 'footer' },
    { key: 'preheader', type: 'text', label: 'Preheader', group: 'content', maxLength: 140 },
    { key: 'logo', type: 'image', label: 'Logo', group: 'brand', recommendedSize: '240 x 80 px' },
    { key: 'heading', type: 'text', label: 'Heading', group: 'content', maxLength: 80 },
    { key: 'intro', type: 'textarea', label: 'Introduction', group: 'content', maxLength: 320, rows: 4 },
    { key: 'articles', type: 'article-list', label: 'Articles', group: 'content', maxItems: 10 },
    { key: 'primaryCta', type: 'button', label: 'Primary button', group: 'buttons' },
    { key: 'showArticleImages', type: 'toggle', label: 'Show article images', group: 'images' },
    { key: 'shareText', type: 'text', label: 'Share prompt', group: 'footer', maxLength: 100 },
    { key: 'shareLink', type: 'link', label: 'Share link', group: 'footer' },
    { key: 'showSocialLinks', type: 'toggle', label: 'Show social links', group: 'footer' },
    { key: 'showFooterText', type: 'toggle', label: 'Show delivery notice', group: 'footer' },
    { key: 'showLegalLinks', type: 'toggle', label: 'Show legal links', group: 'footer' },
    { key: 'socialLinks', type: 'link-list', label: 'Social links', group: 'footer', maxItems: 10, visibilityFieldKey: 'showSocialLinks' },
    { key: 'footerText', type: 'textarea', label: 'Delivery notice', group: 'footer', maxLength: 300, rows: 3, visibilityFieldKey: 'showFooterText' },
    { key: 'legalLinks', type: 'link-list', label: 'Legal links', group: 'footer', maxItems: 10, visibilityFieldKey: 'showLegalLinks' },
    ...THEME_COLOR_FIELDS,
  ],
  editorSections: [
    { id: 'preheader', label: 'Preheader', fieldKeys: ['preheader'], hiddenFieldLabels: ['preheader'], visibilityFieldKey: 'showPreheader' },
    { id: 'header', label: 'Header', fieldKeys: ['logo', 'heading', 'intro', 'primaryCta'], visibilityFieldKey: 'showHeader' },
    { id: 'articles', label: 'Articles', fieldKeys: ['articles'], hiddenFieldLabels: ['articles'], visibilityFieldKey: 'showArticles' },
    {
      id: 'footer',
      label: 'Footer',
      fieldKeys: ['shareText', 'shareLink', 'socialLinks', 'footerText', 'legalLinks'],
      visibilityFieldKey: 'showFooter',
    },
    { id: 'appearance', label: 'Appearance', fieldKeys: THEME_COLOR_FIELD_KEYS },
  ],
  topLevelFieldKeys: ['showArticleImages'],
} as const satisfies TemplateManifest;
