import type { TemplateManifest } from '../../types';
import { createTheme, THEME_COLOR_FIELD_KEYS, THEME_COLOR_FIELDS } from './shared';

const promoHero = {
  remoteUrl: 'https://raw.githubusercontent.com/AlinaZolotavina/email-template-studio/main/public/template-assets/promo-hero.png',
  localPreviewUrl: `${import.meta.env.BASE_URL}template-assets/promo-hero.png`,
  alt: 'Minimal product display with vase and geometric forms',
};

export const newsletterPromoManifest = {
  id: 'newsletter-promo',
  name: 'Promotional offer',
  category: 'newsletter',
  description: 'A campaign layout centered on one offer and its benefits.',
  thumbnailPath: 'template-thumbnails/newsletter-promo.png',
  defaults: {
    templateId: 'newsletter-promo',
    schemaVersion: 1,
    theme: createTheme({
      backgroundColor: '#FFF7ED',
      accentColor: '#C2410C',
    }),
    fields: {
      showPreheader: true,
      showHeader: true,
      showAction: true,
      showFooter: true,
      preheader: 'A limited offer created for our subscribers.',
      logo: { remoteUrl: '', alt: 'Company logo' },
      heroImage: promoHero,
      eyebrow: 'LIMITED TIME OFFER',
      heading: '20% OFF SITEWIDE',
      offerText: 'Our way of saying thank you. Enjoy 20% off everything, for a limited time only.',
      benefits: [
        { label: 'OK', text: 'QUALITY YOU CAN TRUST' },
        { label: 'FAST', text: 'FAST & RELIABLE SHIPPING' },
        { label: 'EASY', text: 'EASY RETURNS, NO HASSLE' },
      ],
      primaryCta: { label: 'SHOP NOW', url: 'https://example.com/offer' },
      showBenefits: true,
      termsText: 'Offer valid through May 25, 2026 at 11:59 PM PT. Exclusions apply. Discount shown at checkout.',
      footerText: "You're receiving this email because you signed up for updates.",
      footerLinks: [
        { label: 'Email', url: 'mailto:hello@example.com' },
        { label: 'IG', url: 'https://example.com/instagram' },
        { label: 'f', url: 'https://example.com/facebook' },
        { label: 'Unsubscribe', url: 'https://example.com/unsubscribe' },
        { label: 'Manage preferences', url: 'https://example.com/preferences' },
      ],
      address: '1234 Market St, Suite 567, San Francisco, CA 94103',
    },
  },
  fields: [
    { key: 'showPreheader', type: 'toggle', label: 'Show preheader', group: 'content' },
    { key: 'showHeader', type: 'toggle', label: 'Show header', group: 'content' },
    { key: 'showAction', type: 'toggle', label: 'Show call to action', group: 'buttons' },
    { key: 'showFooter', type: 'toggle', label: 'Show footer', group: 'footer' },
    { key: 'preheader', type: 'text', label: 'Preheader', group: 'content', maxLength: 140 },
    { key: 'logo', type: 'image', label: 'Logo', group: 'brand', recommendedSize: '240 x 80 px' },
    { key: 'heroImage', type: 'image', label: 'Hero image', group: 'images', recommendedSize: '1200 x 720 px' },
    { key: 'eyebrow', type: 'text', label: 'Eyebrow', group: 'content', maxLength: 50 },
    { key: 'heading', type: 'text', label: 'Heading', group: 'content', maxLength: 90 },
    { key: 'offerText', type: 'textarea', label: 'Offer description', group: 'content', maxLength: 360, rows: 4 },
    { key: 'benefits', type: 'benefit-list', label: 'Benefits', group: 'content', maxItems: 10 },
    { key: 'primaryCta', type: 'link', label: 'Primary button', group: 'buttons' },
    { key: 'showBenefits', type: 'toggle', label: 'Show benefits', group: 'content' },
    { key: 'termsText', type: 'textarea', label: 'Offer terms', group: 'footer', maxLength: 400, rows: 3 },
    { key: 'footerText', type: 'textarea', label: 'Footer text', group: 'footer', maxLength: 300, rows: 3 },
    { key: 'footerLinks', type: 'link-list', label: 'Footer links', group: 'footer', maxItems: 10 },
    { key: 'address', type: 'textarea', label: 'Business address', group: 'footer', maxLength: 300, rows: 2 },
    ...THEME_COLOR_FIELDS,
  ],
  editorSections: [
    { id: 'preheader', label: 'Preheader', fieldKeys: ['preheader'], hiddenFieldLabels: ['preheader'], visibilityFieldKey: 'showPreheader' },
    { id: 'header', label: 'Header', fieldKeys: ['logo', 'heroImage', 'eyebrow', 'heading', 'offerText'], visibilityFieldKey: 'showHeader' },
    { id: 'benefits', label: 'Benefits', fieldKeys: ['showBenefits', 'benefits'], hiddenFieldLabels: ['benefits'], visibilityFieldKey: 'showBenefits' },
    { id: 'action', label: 'Call to action', fieldKeys: ['primaryCta'], visibilityFieldKey: 'showAction' },
    {
      id: 'footer',
      label: 'Footer',
      fieldKeys: ['termsText', 'footerText', 'footerLinks', 'address'],
      hiddenFieldLabels: ['footerLinks'],
      visibilityFieldKey: 'showFooter',
    },
    { id: 'appearance', label: 'Appearance', fieldKeys: THEME_COLOR_FIELD_KEYS },
  ],
} as const satisfies TemplateManifest;
