import type { TemplateManifest } from '../../types';
import { createTheme, THEME_COLOR_FIELD_KEYS, THEME_COLOR_FIELDS } from './shared';

const asset = (name: string, alt: string) => ({
  remoteUrl: `https://raw.githubusercontent.com/AlinaZolotavina/email-template-studio/main/public/template-assets/${name}`,
  localPreviewUrl: `${import.meta.env.BASE_URL}template-assets/${name}`,
  alt,
});

export const newsletterDigestManifest = {
  id: 'newsletter-digest',
  name: 'Weekly digest',
  category: 'newsletter',
  description: 'A compact newsletter with three editorial highlights.',
  thumbnailPath: 'template-thumbnails/newsletter-digest.png',
  defaults: {
    templateId: 'newsletter-digest',
    schemaVersion: 1,
    theme: createTheme({ accentColor: '#0F766E' }),
    fields: {
      preheader: 'This week: product thinking, design systems, and growth.',
      logo: { remoteUrl: '', alt: 'Weekly Digest logo' },
      heading: 'Weekly digest',
      intro: 'Your weekly dose of insights, ideas, and inspiration.',
      article1Category: 'STRATEGY',
      article1Title: 'Five ways to build better habits',
      article1Text: 'Small changes, when done consistently, can lead to big results.',
      article1Image: asset('digest-strategy.png', 'Abstract mountains and sun'),
      article1Link: { label: 'Read more ->', url: 'https://example.com/article-1' },
      article2Category: 'DATA',
      article2Title: 'What the numbers are telling us',
      article2Text: 'Key takeaways from the latest industry trends.',
      article2Image: asset('digest-data.png', 'Ascending data chart'),
      article2Link: { label: 'Read more ->', url: 'https://example.com/article-2' },
      article3Category: 'CULTURE',
      article3Title: 'Creating a culture of feedback',
      article3Text: 'Why feedback matters - and how to make it part of your everyday.',
      article3Image: asset('digest-culture.png', 'Conversation and feedback'),
      article3Link: { label: 'Read more ->', url: 'https://example.com/article-3' },
      primaryCta: { label: "Read this week's top stories", url: 'https://example.com/stories' },
      showArticleImages: true,
      shareText: 'Enjoying the digest?',
      shareLink: { label: 'Share it with a friend.', url: 'https://example.com/share' },
      socialX: { label: 'X', url: 'https://example.com/x' },
      socialLinkedIn: { label: 'in', url: 'https://example.com/linkedin' },
      socialEmail: { label: 'Email', url: 'mailto:hello@example.com' },
      footerText: "You're receiving this email because you signed up for our updates.",
      preferencesLink: { label: 'Update preferences', url: 'https://example.com/preferences' },
      unsubscribeLink: { label: 'Unsubscribe', url: 'https://example.com/unsubscribe' },
    },
  },
  fields: [
    { key: 'preheader', type: 'text', label: 'Preheader', group: 'content', maxLength: 140 },
    { key: 'logo', type: 'image', label: 'Logo', group: 'brand', recommendedSize: '240 x 80 px' },
    { key: 'heading', type: 'text', label: 'Heading', group: 'content', maxLength: 80 },
    { key: 'intro', type: 'textarea', label: 'Introduction', group: 'content', maxLength: 320, rows: 4 },
    { key: 'article1Title', type: 'text', label: 'Article 1 title', group: 'content', maxLength: 100 },
    { key: 'article1Category', type: 'text', label: 'Article 1 category', group: 'content', maxLength: 30 },
    { key: 'article1Text', type: 'textarea', label: 'Article 1 summary', group: 'content', maxLength: 280, rows: 3 },
    { key: 'article1Image', type: 'image', label: 'Article 1 image', group: 'images', recommendedSize: '1120 x 560 px' },
    { key: 'article1Link', type: 'link', label: 'Article 1 link', group: 'content' },
    { key: 'article2Title', type: 'text', label: 'Article 2 title', group: 'content', maxLength: 100 },
    { key: 'article2Category', type: 'text', label: 'Article 2 category', group: 'content', maxLength: 30 },
    { key: 'article2Text', type: 'textarea', label: 'Article 2 summary', group: 'content', maxLength: 280, rows: 3 },
    { key: 'article2Image', type: 'image', label: 'Article 2 image', group: 'images', recommendedSize: '1120 x 560 px' },
    { key: 'article2Link', type: 'link', label: 'Article 2 link', group: 'content' },
    { key: 'article3Title', type: 'text', label: 'Article 3 title', group: 'content', maxLength: 100 },
    { key: 'article3Category', type: 'text', label: 'Article 3 category', group: 'content', maxLength: 30 },
    { key: 'article3Text', type: 'textarea', label: 'Article 3 summary', group: 'content', maxLength: 280, rows: 3 },
    { key: 'article3Image', type: 'image', label: 'Article 3 image', group: 'images', recommendedSize: '1120 x 560 px' },
    { key: 'article3Link', type: 'link', label: 'Article 3 link', group: 'content' },
    { key: 'primaryCta', type: 'link', label: 'Primary button', group: 'buttons' },
    { key: 'showArticleImages', type: 'toggle', label: 'Show article images', group: 'images' },
    { key: 'shareText', type: 'text', label: 'Share prompt', group: 'footer', maxLength: 100 },
    { key: 'shareLink', type: 'link', label: 'Share link', group: 'footer' },
    { key: 'socialX', type: 'link', label: 'X link', group: 'footer' },
    { key: 'socialLinkedIn', type: 'link', label: 'LinkedIn link', group: 'footer' },
    { key: 'socialEmail', type: 'link', label: 'Email link', group: 'footer' },
    { key: 'footerText', type: 'textarea', label: 'Footer text', group: 'footer', maxLength: 300, rows: 3 },
    { key: 'preferencesLink', type: 'link', label: 'Preferences link', group: 'footer' },
    { key: 'unsubscribeLink', type: 'link', label: 'Unsubscribe link', group: 'footer' },
    ...THEME_COLOR_FIELDS,
  ],
  editorSections: [
    { id: 'preheader', label: 'Preheader', fieldKeys: ['preheader'] },
    { id: 'header', label: 'Header', fieldKeys: ['logo', 'heading', 'intro', 'primaryCta'] },
    {
      id: 'article-1',
      label: 'Article 1',
      fieldKeys: ['article1Image', 'article1Category', 'article1Title', 'article1Text', 'article1Link'],
    },
    {
      id: 'article-2',
      label: 'Article 2',
      fieldKeys: ['article2Image', 'article2Category', 'article2Title', 'article2Text', 'article2Link'],
    },
    {
      id: 'article-3',
      label: 'Article 3',
      fieldKeys: ['article3Image', 'article3Category', 'article3Title', 'article3Text', 'article3Link'],
    },
    {
      id: 'footer',
      label: 'Footer',
      fieldKeys: ['showArticleImages', 'shareText', 'shareLink', 'socialX', 'socialLinkedIn', 'socialEmail', 'footerText', 'preferencesLink', 'unsubscribeLink'],
    },
    { id: 'appearance', label: 'Appearance', fieldKeys: THEME_COLOR_FIELD_KEYS },
  ],
} as const satisfies TemplateManifest;
