import type { TemplateManifest } from '../../types';
import { createTheme, THEME_COLOR_FIELD_KEYS, THEME_COLOR_FIELDS } from './shared';

export const welcomeOnboardingManifest = {
  id: 'welcome-onboarding',
  name: 'Onboarding steps',
  category: 'welcome',
  description: 'A welcome email that guides readers through three first steps.',
  thumbnailPath: 'template-thumbnails/welcome-onboarding.png',
  defaults: {
    templateId: 'welcome-onboarding',
    schemaVersion: 1,
    theme: createTheme({ accentColor: '#0369A1' }),
    fields: {
      showPreheader: true,
      showHeader: true,
      showAction: true,
      showFooter: true,
      preheader: 'Three quick steps to get value from your new workspace.',
      logo: { remoteUrl: '', alt: 'Company logo' },
      greeting: 'Welcome aboard!',
      intro: "We're excited to have you here. Follow these 3 simple steps to get started.",
      steps: [
        { title: 'Complete your profile', text: 'Add a few details about yourself so we can personalize your experience.' },
        { title: 'Set up your workspace', text: 'Create your workspace and invite your team to collaborate.' },
        { title: 'Take your first action', text: 'Explore key features and take your first step to success.' },
      ],
      primaryCta: { label: 'Get started', url: 'https://example.com/onboarding', backgroundColor: '#0369A1', textColor: '#FFFFFF' },
      showSupport: true,
      supportText: "Need help? We're here for you.",
      supportLink: { label: 'Visit our Help Center ->', url: 'https://example.com/support' },
      signoffText: 'The simplest way to get things done.',
      footerText: 'This email was sent to you. You are receiving this email because you created an account.',
      footerLinks: [
        { label: 'Unsubscribe', url: 'https://example.com/unsubscribe' },
        { label: 'Privacy Policy', url: 'https://example.com/privacy' },
        { label: 'Terms of Service', url: 'https://example.com/terms' },
      ],
    },
  },
  fields: [
    { key: 'showPreheader', type: 'toggle', label: 'Show preheader', group: 'content' },
    { key: 'showHeader', type: 'toggle', label: 'Show header', group: 'content' },
    { key: 'showAction', type: 'toggle', label: 'Show call to action', group: 'buttons' },
    { key: 'showFooter', type: 'toggle', label: 'Show footer', group: 'footer' },
    { key: 'preheader', type: 'text', label: 'Preheader', group: 'content', maxLength: 140 },
    { key: 'logo', type: 'image', label: 'Logo', group: 'brand', recommendedSize: '240 x 80 px' },
    { key: 'greeting', type: 'text', label: 'Greeting', group: 'content', maxLength: 90 },
    { key: 'intro', type: 'textarea', label: 'Introduction', group: 'content', maxLength: 360, rows: 4 },
    { key: 'steps', type: 'step-list', label: 'Steps', group: 'content' },
    { key: 'primaryCta', type: 'button', label: 'Primary button', group: 'buttons' },
    { key: 'showSupport', type: 'toggle', label: 'Show support link', group: 'footer' },
    { key: 'supportText', type: 'text', label: 'Support prompt', group: 'footer', maxLength: 140 },
    { key: 'supportLink', type: 'link', label: 'Support link', group: 'footer' },
    { key: 'signoffText', type: 'text', label: 'Sign-off text', group: 'footer', maxLength: 140 },
    { key: 'footerText', type: 'textarea', label: 'Footer text', group: 'footer', maxLength: 300, rows: 3 },
    { key: 'footerLinks', type: 'link-list', label: 'Footer links', group: 'footer', maxItems: 10 },
    ...THEME_COLOR_FIELDS,
  ],
  editorSections: [
    { id: 'preheader', label: 'Preheader', fieldKeys: ['preheader'], hiddenFieldLabels: ['preheader'], visibilityFieldKey: 'showPreheader' },
    { id: 'header', label: 'Header', fieldKeys: ['logo', 'greeting', 'intro'], visibilityFieldKey: 'showHeader' },
    { id: 'steps', label: 'Steps', fieldKeys: ['steps'], hiddenFieldLabels: ['steps'] },
    {
      id: 'action',
      label: 'Call to action',
      fieldKeys: ['primaryCta', 'showSupport', 'supportText', 'supportLink'],
      visibilityFieldKey: 'showAction',
    },
    {
      id: 'footer',
      label: 'Footer',
      fieldKeys: ['signoffText', 'footerText', 'footerLinks'],
      hiddenFieldLabels: ['footerLinks'],
      visibilityFieldKey: 'showFooter',
    },
    { id: 'appearance', label: 'Appearance', fieldKeys: THEME_COLOR_FIELD_KEYS },
  ],
} as const satisfies TemplateManifest;
