import type { TemplateManifest } from '../../types';
import { createTheme, THEME_COLOR_FIELD_KEYS, THEME_COLOR_FIELDS } from './shared';

export const welcomeSimpleManifest = {
  id: 'welcome-simple',
  name: 'Simple welcome',
  category: 'welcome',
  description: 'A direct welcome message with one clear next action.',
  thumbnailPath: 'template-thumbnails/welcome-simple.png',
  defaults: {
    templateId: 'welcome-simple',
    schemaVersion: 1,
    theme: createTheme({ accentColor: '#7C3AED' }),
    fields: {
      preheader: 'Welcome - your account is ready.',
      logo: { remoteUrl: '', alt: 'Company logo' },
      greeting: 'Welcome!',
      subheading: "We're glad you're here.",
      body: "You're all set to get started. Take a moment to explore and see what you can do.",
      primaryCta: { label: 'Complete your profile ->', url: 'https://example.com/app' },
      helpText: 'Need help?',
      helpLink: { label: 'Visit our Help Center.', url: 'https://example.com/help' },
      socialEmail: { label: 'Email', url: 'mailto:hello@example.com' },
      socialX: { label: 'X', url: 'https://example.com/x' },
      socialChat: { label: 'Chat', url: 'https://example.com/chat' },
      footerText: "You're receiving this email because you recently created an account with us.",
      unsubscribeLink: { label: 'Unsubscribe', url: 'https://example.com/unsubscribe' },
    },
  },
  fields: [
    { key: 'preheader', type: 'text', label: 'Preheader', group: 'content', maxLength: 140 },
    { key: 'logo', type: 'image', label: 'Logo', group: 'brand', recommendedSize: '240 x 80 px' },
    { key: 'greeting', type: 'text', label: 'Greeting', group: 'content', maxLength: 90 },
    { key: 'subheading', type: 'text', label: 'Subheading', group: 'content', maxLength: 140 },
    { key: 'body', type: 'textarea', label: 'Message', group: 'content', maxLength: 600, rows: 6 },
    { key: 'primaryCta', type: 'link', label: 'Primary button', group: 'buttons' },
    { key: 'helpText', type: 'text', label: 'Help prompt', group: 'footer', maxLength: 100 },
    { key: 'helpLink', type: 'link', label: 'Help center link', group: 'footer' },
    { key: 'socialEmail', type: 'link', label: 'Email link', group: 'footer' },
    { key: 'socialX', type: 'link', label: 'X link', group: 'footer' },
    { key: 'socialChat', type: 'link', label: 'Chat link', group: 'footer' },
    { key: 'footerText', type: 'textarea', label: 'Footer text', group: 'footer', maxLength: 300, rows: 3 },
    { key: 'unsubscribeLink', type: 'link', label: 'Unsubscribe link', group: 'footer' },
    ...THEME_COLOR_FIELDS,
  ],
  editorSections: [
    { id: 'preheader', label: 'Preheader', fieldKeys: ['preheader'] },
    { id: 'header', label: 'Header', fieldKeys: ['logo', 'greeting', 'subheading'] },
    { id: 'message', label: 'Message', fieldKeys: ['body'] },
    { id: 'action', label: 'Call to action', fieldKeys: ['primaryCta'] },
    {
      id: 'footer',
      label: 'Footer',
      fieldKeys: ['helpText', 'helpLink', 'socialEmail', 'socialX', 'socialChat', 'footerText', 'unsubscribeLink'],
    },
    { id: 'appearance', label: 'Appearance', fieldKeys: THEME_COLOR_FIELD_KEYS },
  ],
} as const satisfies TemplateManifest;
