import type { TemplateManifest } from '../../types';
import { createTheme, THEME_COLOR_FIELD_KEYS, THEME_COLOR_FIELDS } from './shared';

export const welcomeOnboardingManifest = {
  id: 'welcome-onboarding',
  name: 'Onboarding steps',
  category: 'welcome',
  description: 'A welcome email that guides readers through three first steps.',
  thumbnailPath: 'template-thumbnails/welcome-onboarding.png',
  defaults: {
    templateId: 'welcome-onboarding',
    schemaVersion: 1,
    theme: createTheme({ accentColor: '#0369A1' }),
    fields: {
      preheader: 'Three quick steps to get value from your new workspace.',
      logo: { remoteUrl: '', alt: 'Company logo' },
      greeting: 'Welcome aboard!',
      intro: "We're excited to have you here. Follow these 3 simple steps to get started.",
      step1Title: 'Complete your profile',
      step1Text: 'Add a few details about yourself so we can personalize your experience.',
      step2Title: 'Set up your workspace',
      step2Text: 'Create your workspace and invite your team to collaborate.',
      step3Title: 'Take your first action',
      step3Text: 'Explore key features and take your first step to success.',
      primaryCta: { label: 'Get started', url: 'https://example.com/onboarding' },
      showSupport: true,
      supportText: "Need help? We're here for you.",
      supportLink: { label: 'Visit our Help Center ->', url: 'https://example.com/support' },
      signoffText: 'The simplest way to get things done.',
      footerText: 'This email was sent to you. You are receiving this email because you created an account.',
      unsubscribeLink: { label: 'Unsubscribe', url: 'https://example.com/unsubscribe' },
      privacyLink: { label: 'Privacy Policy', url: 'https://example.com/privacy' },
      termsLink: { label: 'Terms of Service', url: 'https://example.com/terms' },
    },
  },
  fields: [
    { key: 'preheader', type: 'text', label: 'Preheader', group: 'content', maxLength: 140 },
    { key: 'logo', type: 'image', label: 'Logo', group: 'brand', recommendedSize: '240 x 80 px' },
    { key: 'greeting', type: 'text', label: 'Greeting', group: 'content', maxLength: 90 },
    { key: 'intro', type: 'textarea', label: 'Introduction', group: 'content', maxLength: 360, rows: 4 },
    { key: 'step1Title', type: 'text', label: 'Step 1 title', group: 'content', maxLength: 80 },
    { key: 'step1Text', type: 'textarea', label: 'Step 1 description', group: 'content', maxLength: 240, rows: 3 },
    { key: 'step2Title', type: 'text', label: 'Step 2 title', group: 'content', maxLength: 80 },
    { key: 'step2Text', type: 'textarea', label: 'Step 2 description', group: 'content', maxLength: 240, rows: 3 },
    { key: 'step3Title', type: 'text', label: 'Step 3 title', group: 'content', maxLength: 80 },
    { key: 'step3Text', type: 'textarea', label: 'Step 3 description', group: 'content', maxLength: 240, rows: 3 },
    { key: 'primaryCta', type: 'link', label: 'Primary button', group: 'buttons' },
    { key: 'showSupport', type: 'toggle', label: 'Show support link', group: 'footer' },
    { key: 'supportText', type: 'text', label: 'Support prompt', group: 'footer', maxLength: 140 },
    { key: 'supportLink', type: 'link', label: 'Support link', group: 'footer' },
    { key: 'signoffText', type: 'text', label: 'Sign-off text', group: 'footer', maxLength: 140 },
    { key: 'footerText', type: 'textarea', label: 'Footer text', group: 'footer', maxLength: 300, rows: 3 },
    { key: 'unsubscribeLink', type: 'link', label: 'Unsubscribe link', group: 'footer' },
    { key: 'privacyLink', type: 'link', label: 'Privacy link', group: 'footer' },
    { key: 'termsLink', type: 'link', label: 'Terms link', group: 'footer' },
    ...THEME_COLOR_FIELDS,
  ],
  editorSections: [
    { id: 'preheader', label: 'Preheader', fieldKeys: ['preheader'] },
    { id: 'header', label: 'Header', fieldKeys: ['logo', 'greeting', 'intro'] },
    { id: 'step-1', label: 'Step 1', fieldKeys: ['step1Title', 'step1Text'] },
    { id: 'step-2', label: 'Step 2', fieldKeys: ['step2Title', 'step2Text'] },
    { id: 'step-3', label: 'Step 3', fieldKeys: ['step3Title', 'step3Text'] },
    {
      id: 'action',
      label: 'Call to action',
      fieldKeys: ['primaryCta', 'showSupport', 'supportText', 'supportLink'],
    },
    {
      id: 'footer',
      label: 'Footer',
      fieldKeys: ['signoffText', 'footerText', 'unsubscribeLink', 'privacyLink', 'termsLink'],
    },
    { id: 'appearance', label: 'Appearance', fieldKeys: THEME_COLOR_FIELD_KEYS },
  ],
} as const satisfies TemplateManifest;
