import type { TemplateManifest } from '../../types';
import { createTheme, THEME_COLOR_FIELD_KEYS, THEME_COLOR_FIELDS } from './shared';

export const welcomeSimpleManifest = {
  id: 'welcome-simple',
  name: 'Simple welcome',
  category: 'welcome',
  description: 'A direct welcome message with one clear next action.',
  thumbnailPath: 'template-thumbnails/welcome-simple.png',
  defaults: {
    templateId: 'welcome-simple',
    schemaVersion: 1,
    theme: createTheme({ accentColor: '#7C3AED' }),
    fields: {
      showPreheader: true,
      showHeader: true,
      showMessage: true,
      showAction: true,
      showFooter: true,
      preheader: 'Welcome - your account is ready.',
      logo: { remoteUrl: '', alt: 'Company logo' },
      greeting: 'Welcome!',
      subheading: "We're glad you're here.",
      body: "You're all set to get started. Take a moment to explore and see what you can do.",
      primaryCta: { label: 'Complete your profile ->', url: 'https://example.com/app', backgroundColor: '#7C3AED', textColor: '#FFFFFF' },
      helpText: 'Need help?',
      footerText: "You're receiving this email because you recently created an account with us.",
      footerLinks: [
        { label: 'Visit our Help Center.', url: 'https://example.com/help' },
        { label: 'Email', url: 'mailto:hello@example.com' },
        { label: 'X', url: 'https://example.com/x' },
        { label: 'Chat', url: 'https://example.com/chat' },
        { label: 'Unsubscribe', url: 'https://example.com/unsubscribe' },
      ],
    },
  },
  fields: [
    { key: 'showPreheader', type: 'toggle', label: 'Show preheader', group: 'content' },
    { key: 'showHeader', type: 'toggle', label: 'Show header', group: 'content' },
    { key: 'showMessage', type: 'toggle', label: 'Show message', group: 'content' },
    { key: 'showAction', type: 'toggle', label: 'Show call to action', group: 'buttons' },
    { key: 'showFooter', type: 'toggle', label: 'Show footer', group: 'footer' },
    { key: 'preheader', type: 'text', label: 'Preheader', group: 'content', maxLength: 140 },
    { key: 'logo', type: 'image', label: 'Logo', group: 'brand', recommendedSize: '240 x 80 px' },
    { key: 'greeting', type: 'text', label: 'Greeting', group: 'content', maxLength: 90 },
    { key: 'subheading', type: 'text', label: 'Subheading', group: 'content', maxLength: 140 },
    { key: 'body', type: 'textarea', label: 'Message', group: 'content', maxLength: 600, rows: 6 },
    { key: 'primaryCta', type: 'button', label: 'Primary button', group: 'buttons' },
    { key: 'helpText', type: 'text', label: 'Help prompt', group: 'footer', maxLength: 100 },
    { key: 'footerText', type: 'textarea', label: 'Footer text', group: 'footer', maxLength: 300, rows: 3 },
    { key: 'footerLinks', type: 'link-list', label: 'Footer links', group: 'footer', maxItems: 10 },
    ...THEME_COLOR_FIELDS,
  ],
  editorSections: [
    { id: 'preheader', label: 'Preheader', fieldKeys: ['preheader'], hiddenFieldLabels: ['preheader'], visibilityFieldKey: 'showPreheader' },
    { id: 'header', label: 'Header', fieldKeys: ['logo', 'greeting', 'subheading'], visibilityFieldKey: 'showHeader' },
    { id: 'message', label: 'Message', fieldKeys: ['body'], visibilityFieldKey: 'showMessage' },
    { id: 'action', label: 'Call to action', fieldKeys: ['primaryCta'], visibilityFieldKey: 'showAction' },
    {
      id: 'footer',
      label: 'Footer',
      fieldKeys: ['helpText', 'footerLinks', 'footerText'],
      hiddenFieldLabels: ['footerLinks'],
      visibilityFieldKey: 'showFooter',
    },
    { id: 'appearance', label: 'Appearance', fieldKeys: THEME_COLOR_FIELD_KEYS },
  ],
} as const satisfies TemplateManifest;
